name: deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Script in server
        uses: jujuwon/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd amond-landing
            git pull
            ./release.sh
